[package]
name = "word_lookup"
version = "0.1.2"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.10", features = ["json"] }
clap = "3.1.6"
serde_json = "1.0.64"
tokio = { version = "1", features = ["full"] }
